apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
  namespace: devops
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: LoadBalancer
