apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: younes111/frontend-app:v1.0
          env:
            - name: API_URL
              value: "http://34.79.55.22:8089" # Utilisation du nom du service Kubernetes pour l'accès au backend
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
